Add document for setting filecoindot
ChainSafe/filecoindot pull request #70
Opened 2021-11-08 07:59 UTC by clearloop

## Changes

- [x] add docs in `/README.md`
  - [x] configure runtime
  - [x] add signer account
  - [x] set rpc endpoint

## Tests

```

```

## Issues

- Closes #63

2021-11-08 09:12 UTC, mattsse requested changes
some nits,
can we move the ocw demo into the ocw crate otherwise the main readme is kinda bloated?
Instead, we reference from the root readme

2021-11-08 09:12 UTC, mattsse commented on README.md
> +// ManagerOrigin as root
```suggestion
// ManagerOrigin which manages the approved relayer set, in this case root
```

2021-11-08 09:12 UTC, mattsse commented on README.md
> +    pub const UnsignedPriority: BlockNumber = 3;
add brief explainer

2021-11-08 09:12 UTC, mattsse commented on README.md
> +        );
this looks pretty verbose,

can we either,

* exclude this from the overview?
* explain whats happening/why we need this?
* link to existing offchain worker docs?

2021-11-08 09:12 UTC, mattsse commented on README.md
> +
add link to the subkey command

2021-11-08 09:12 UTC, mattsse commented on README.md
> +the filecoindot offchain work has been set up!
```suggestion
the filecoindot offchain worker has been set up!
```

2021-11-09 08:09 UTC, clearloop commented
This doc missed the `set_relayer` extrinsic, should we doc it with `polkadot.js` or just a brief introduce ( if we serve rust doc in the CI, we can reference it)?

2021-11-09 09:08 UTC, mattsse approved these changes
lgtm

2021-11-09 09:08 UTC, mattsse commented
> This doc missed the `set_relayer` extrinsic, should we doc it with `polkadot.js` or just leave a brief introduce ( if we serve rust doc in the CI, we can reference it)?

I think the pallet docs are sufficient here, set_relayer should be self-explanatory.

2021-11-09 09:09 UTC, merged